# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'surfbreak' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Disk', '~> 0.3.3'
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.11'
  pod 'Firebase/Performance'
  pod 'Fingertips'

  target 'surfbreakTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
